DROP DATABASE IF EXISTS office_db;
CREATE DATABASE office_db;

USE office_db;

CREATE TABLE depts (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (30) NOT NULL,
);

CREATE TABLE roles (
id INT AUTO_INCREMENT PRIMARY KEY,    
title VARCHAR (30) NOT NULL,
salary DECIMAL(10, 2) NOT NULL,
dept_id INT,
FOREIGN KEY (dept_id) REFERENCES depts(id)
);

CREATE TABLE empls (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR (30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
role_id INT, 
manager_id INT,
FOREIGN KEY (role_id) REFERENCES roles(id)
);

